// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "f21d5395759d428ec39d94d3114d90dfab7b555c40dc4c0355a1ce18fc72ce40")
